# Generated by Django 4.2.1 on 2024-11-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_customuser_id_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_perfil',
            field=models.CharField(default='2780d1856be54c6fa79b842cdf0cbeec', editable=False, max_length=32),
        ),
    ]
