# Generated by Django 4.2.1 on 2024-12-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_customuser_id_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_perfil',
            field=models.CharField(default='602c7456b266481f934dbf993d7ff3bf', editable=False, max_length=32),
        ),
    ]
