# Generated by Django 4.2.1 on 2024-12-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_customuser_id_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_perfil',
            field=models.CharField(default='2b5bd90855f1424ba2a45d946b1be814', editable=False, max_length=32),
        ),
    ]
