# Generated by Django 4.2.1 on 2024-12-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_customuser_id_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_perfil',
            field=models.CharField(default='e044b613bd984a079bcfd9eafe704452', editable=False, max_length=32),
        ),
    ]
