# Generated by Django 4.2.1 on 2024-12-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_customuser_id_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_perfil',
            field=models.CharField(default='7f5a5641d8ab409fae19377c89d4c711', editable=False, max_length=32),
        ),
    ]
