# Generated by Django 4.2.1 on 2025-03-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_customuser_id_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_perfil',
            field=models.CharField(default='b2d821f9851e4b4b852d776746686bb9', editable=False, max_length=32),
        ),
    ]
