# Generated by Django 4.2.1 on 2025-03-28 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_alter_customuser_id_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_perfil',
            field=models.CharField(default='6fc58a37cd134c2684050ba1cf110f6b', editable=False, max_length=32),
        ),
    ]
