# Generated by Django 4.2.1 on 2025-03-28 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_alter_customuser_id_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_perfil',
            field=models.CharField(default='5d519895414e48c1a1feb4ee1271e018', editable=False, max_length=32),
        ),
    ]
