# Generated by Django 4.2.1 on 2025-03-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_alter_customuser_id_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_perfil',
            field=models.CharField(default='d973f74f743b403a9f4abf7eb5c81e70', editable=False, max_length=32),
        ),
    ]
