# Generated by Django 4.2.1 on 2025-03-31 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_alter_customuser_id_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_perfil',
            field=models.CharField(default='0cf787a5640243b5af411eca729dc2a6', editable=False, max_length=32),
        ),
    ]
