# Generated by Django 4.2.1 on 2025-04-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_alter_customuser_id_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_perfil',
            field=models.CharField(default='b643bb8f962142c0b38a114f02b08bb1', editable=False, max_length=32),
        ),
    ]
