# Generated by Django 4.2.1 on 2025-04-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_alter_customuser_id_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_perfil',
            field=models.CharField(default='73b29e3948b24d8d96f8d0ac1f9a6ac6', editable=False, max_length=32),
        ),
    ]
