# Generated by Django 4.2.1 on 2025-04-04 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_alter_customuser_id_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_perfil',
            field=models.CharField(default='51ed72fbf4ef4baa8f28f98cd81dc0a4', editable=False, max_length=32),
        ),
    ]
