# Generated by Django 4.2.1 on 2025-04-04 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_alter_customuser_id_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_perfil',
            field=models.CharField(default='780ebbbe9e9a473ab7413237566756db', editable=False, max_length=32),
        ),
    ]
