# Generated by Django 4.2.1 on 2025-04-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_alter_customuser_id_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_perfil',
            field=models.CharField(default='70cfea2164c74894970bdb72243927dc', editable=False, max_length=32),
        ),
    ]
