# Generated by Django 4.2.1 on 2025-03-28 00:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('canvas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvasmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='canvas_models', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
