# Generated by Django 4.2.1 on 2025-03-31 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('problem', models.CharField(max_length=400, unique=True)),
                ('target_age', models.CharField(max_length=3, unique=True)),
                ('target_location', models.CharField(max_length=150, unique=True)),
                ('target_interest', models.CharField(max_length=250, unique=True)),
                ('differential_factor', models.CharField(max_length=250, unique=True)),
                ('communication_type', models.CharField(max_length=15, unique=True)),
                ('call_actions', models.CharField(max_length=250, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_base', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
