# Generated by Django 4.2.1 on 2025-03-31 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybase',
            name='call_actions',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='companybase',
            name='communication_type',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='companybase',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='companybase',
            name='differential_factor',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='companybase',
            name='problem',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='companybase',
            name='target_age',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='companybase',
            name='target_interest',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='companybase',
            name='target_location',
            field=models.CharField(max_length=150),
        ),
    ]
